config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end
  
  def new
    @schedule = Schedule.new
  end
  
  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start_day, :end_day, :all_day, :memo))
    if @schedule.save
      redirect_to schedules_path
      flash[:notice] = "ユーザーを新規登録しました"
    else
      render new_schedule_path
    end
  end
  
  def show
    @schedule = Schedule.find(params[:id])
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start_day, :end_day, :all_day, :memo))
      flash[:notice] = "IDが「#{@schedule.id}」のスケジュールを更新しました"
      redirect_to schedules_path
    else
      render "edit" #edit_schedule_path(@schedule.id)ではできなかった？
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to schedules_path
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <header>
    <h1>Ruby on Rails スケジュール管理アプリ</h1>
  </header>

  <body>
    <%= yield %>
  </body>
  
  <footer>
    <% require "date" %>
    <% now_time = DateTime.now.new_offset(Rational(9, 24)) %>
    <p>現在の日時：<%= now_time.to_s(:datetime_jp) %></p>
    <% if current_page?(schedules_path) %>
      <p>スケジュールの合計：<%= @schedules.count %></p>
    <% end %>
  </footer>

</html>

app/views/schedules/edit.html.erb
<h2>スケジュール編集</h2>

<%= render "shared/error", obj:@schedule %>

<%= form_for @schedule do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :start_day, "開始日" %></th>
      <td><%= f.datetime_select :start_day, minute_step: 10 %></td>
    </tr>
    <tr>
      <th><%= f.label :end_day, "終了日" %></th>
      <td><%= f.datetime_select :end_day, minute_step: 10 %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day, "終日" %></th>
      <td><%= f.check_box  :all_day, {checked: false}, true, false %>終日の場合はチェックします</td>
    </tr>
    <tr>
      <th><%= f.label :memo, "スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>
  <p><%= f.submit "スケジュールの編集を完了する" %></p>
  <p><%= link_to "スケジュール一覧に戻る", schedules_path %></p>
<% end %>

app/views/schedules/index.html.erb
<h2>スケジュール一覧</h2>

<% if flash.notice %>
  <p class="notice"><%= flash.notice %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>スケジュール更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.title %></td>
        <td><%= schedule.start_day %></td>
        <td><%= schedule.end_day %></td>
        <td>
          <% if schedule.all_day %>
            ○
          <% else %>
            ×
          <% end %>
        </td>
        <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "確認", schedule_path(schedule.id) %></td>
        <td><%= link_to "編集", edit_schedule_path(schedule.id) %></td>
        <td><%= link_to "削除", schedule_path(schedule.id), method: :delete, data: { confirm: "本当に削除しますか？"} %></td>
      </tr>
    <% end %>
  </tbody>  
</table>
<p><%= link_to "スケジュール新規登録", new_schedule_path %></p>

app/views/schedules/new.html.erb
<h2>スケジュール新規作成</h2>

<%= render "shared/error", obj:@schedule %>

<%= form_for @schedule do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :start_day, "開始日" %></th>
      <td><%= f.datetime_select :start_day %></td>
    </tr>
    <tr>
      <th><%= f.label :end_day, "終了日" %></th>
      <td><%= f.datetime_select :end_day %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day, "終日" %></th>
      <td><%= f.check_box  :all_day, {checked: false}, true, false %>終日の場合はチェックします</td>
    </tr>
    <tr>
      <th><%= f.label :memo, "スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>
  <p><%= f.submit "スケジュールを新規登録する" %></p>
  <p><%= link_to "スケジュール一覧に戻る", schedules_path %></p>
<% end %>

app/views/schedules/show.html.erb
<h2>スケジュール詳細</h2>
<table>
  <tr>
    <th>タイトル</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @schedule.start_day %></td>
  </tr>
  <tr>
    <th>投稿日時</th>
    <td><%= @schedule.end_day %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td>
      <% if @schedule.all_day %>
        ○
      <% else %>
        ×
      <% end %>
    </td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @schedule.memo %></td>
  </tr>
</table>
<p><%= link_to "スケジュール一覧に戻る", schedules_path %></p>
<p><%= link_to "スケジュールを編集する", edit_schedule_path(@schedule.id) %></p>
<p><%= link_to "スケジュールを削除", schedule_path(@schedule.id), method: :delete, data: { confirm: "本当に削除しますか？"}  %></p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>